In [1]:
result = 0
for i in range (1,10):
    result += 1
print(result)       

9


# Data Analysis
Data analysis is the process of collecting, cleaning, transforming and modeling the data to find out meaningful information to support decision making

# Library
Collection of different modules (numpy, seaborn, pandas, etc)

#pip install numpy

# Numpy 
It is used to work with collection of numbers.
It helps you perform operations on numbers.    

In [2]:
import numpy as np

# Array 
Collection of homogenous data (identical type of data) ordered collection (indexing can be done)

### Difference between Array and List

In [5]:
l1 = [3,4,5,6]
l2 = [7,8,9,10]
l3 = l1 + l2
l3

[3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
l1 = [3,4,5,6]
l2 = [7,8,9,10]
l3 = []
for i in range(len(l1)):
    l3.append(l1[i]+l2[i])
l3    

[10, 12, 14, 16]

In [9]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr3 = arr1 + arr2
arr3

array([ 6,  8, 10, 12])

In [11]:
arr3 = arr2 - arr1
arr3

array([4, 4, 4, 4])

# Vectorization
when we perform opertions on array internally it is performed on elements of array
-Array supports vectorization
-List does not support vectorization (we will have to use loop to perform operation on elements)

In [13]:
arr3 = np.array([10,20,30,40])
arr3*5

array([ 50, 100, 150, 200])

If we add different types of data in array it will convert it in string data type (or biggest datatype from the array)

In [15]:
arr1 = np.array([1, 'Fbs', 56.09])
arr1.dtype

dtype('<U32')

In [16]:
arr2 = np.array([12, 56, 90.3])
arr2.dtype

dtype('float64')

In [17]:
arr3 = np.array([1,2,3])
arr3.dtype

dtype('int64')

In [18]:
arr1.shape

(3,)

In [20]:
arr1.ndim

1

In [21]:
arr1.size

3

In [22]:
arr = np.array([24, 30 , 28])
arr > 25

array([False,  True,  True])

In [26]:
%%time
l1 = [x for x in range(1,10001)]
l2 = [x for x in range(10001,20001)]
l3 = []
for i in range(len(l1)):
    l3.append(l1[i]+l2[i])
#To check CPU time and walltime for execution    

CPU times: total: 0 ns
Wall time: 13.6 ms


In [27]:
%%time
arr1 = np.array([x for x in range(1,10001)])
arr2 = np.array([x for x in range(10001,20001)])
arr3 = arr1 + arr2

CPU times: total: 0 ns
Wall time: 5.3 ms


In [33]:
import sys
l1 = [34,56,78,90]
sys.getsizeof (l1[0] * len(l1))
#space taken

28

In [32]:
arr = np.array([34,56,78,90])
arr.itemsize * arr.size

32

In [34]:
arr1 = np.array([[1,2,3], [6,7,8]])
arr1

array([[1, 2, 3],
       [6, 7, 8]])

In [35]:
arr1.ndim

2

In [36]:
arr1.size

6

In [37]:
arr1.shape

(2, 3)

In [3]:
arr2 = np.array ([[[1,2,3],
                   [4,5,6]],
                  [[7,8,9],
                   [10,11,12]]])
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [4]:
arr2.shape

(2, 2, 3)

In [5]:
arr2.ndim

3

# Operations on Array

In [6]:
arr1 = np.arange(1,21)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [7]:
arr2 = np.arange(1,25,2)
arr2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [8]:
arr1 = np.random.randint(1,100,15)
arr1

array([83, 54, 88, 59, 31, 90, 47, 90, 97, 55, 19, 37, 99, 99, 75],
      dtype=int32)

In [9]:
arr1[2]

np.int32(88)

In [10]:
arr1[-2]

np.int32(99)

In [11]:
arr1[0:4]

array([83, 54, 88, 59], dtype=int32)

In [12]:
arr1[ :6]

array([83, 54, 88, 59, 31, 90], dtype=int32)

In [13]:
arr1[ ::-1]

array([75, 99, 99, 37, 19, 55, 97, 90, 47, 90, 31, 59, 88, 54, 83],
      dtype=int32)

In [14]:
arr1.min()

np.int32(19)

In [15]:
arr1.max()

np.int32(99)

In [16]:
arr1.sum()

np.int64(1023)

In [17]:
arr1.mean()

np.float64(68.2)

In [19]:
arr1.shape

(15,)

In [24]:
arr1 = arr1.reshape(3,5)

In [25]:
arr1.shape

(3, 5)

In [26]:
arr1

array([[83, 54, 88, 59, 31],
       [90, 47, 90, 97, 55],
       [19, 37, 99, 99, 75]], dtype=int32)

In [27]:
arr1[0]

array([83, 54, 88, 59, 31], dtype=int32)

In [28]:
arr1[2]

array([19, 37, 99, 99, 75], dtype=int32)

In [29]:
arr1[0,0]

np.int32(83)

In [30]:
arr1[1,3]

np.int32(97)

In [32]:
arr2 = np.random.randint(1,100,25)
arr2 = arr2.reshape(5,5)
arr2

array([[91, 56, 96, 69,  9],
       [ 2, 67, 98, 58, 82],
       [56, 73, 52, 70,  2],
       [50, 92,  5, 97, 73],
       [40, 33, 82, 97, 35]], dtype=int32)

In [33]:
arr2[0:3]

array([[91, 56, 96, 69,  9],
       [ 2, 67, 98, 58, 82],
       [56, 73, 52, 70,  2]], dtype=int32)

In [34]:
arr2[2:4,0:2]

array([[56, 73],
       [50, 92]], dtype=int32)

# Some attributes

In [36]:
arr1 = np.linspace(1,10)
arr1

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [38]:
arr2 = np.random.rand(10)
arr2

array([0.43264317, 0.17672876, 0.07051349, 0.44883039, 0.76277144,
       0.61012823, 0.62341917, 0.97031401, 0.43280104, 0.43121496])

In [41]:
arr3 = np.ones(5, dtype ='int')
#arr3 = np.ones(5)
arr3

array([1, 1, 1, 1, 1])

In [43]:
arr4 = np.zeros(10)
arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
arr5 = np.eye(3,3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
arr1 = np.random.randint(1,100,30).reshape(6,5)
arr1

array([[33, 41, 72, 50, 87],
       [ 7, 18, 37, 72, 32],
       [22, 34, 35, 48, 18],
       [68, 84, 75, 80, 62],
       [ 8, 68, 75, 49, 68],
       [26, 62, 59, 97, 83]], dtype=int32)

In [46]:
arr1.min()

np.int32(7)

In [50]:
arr1[0].min()
#gives min number from first column

np.int32(33)

In [51]:
arr1.min(axis=0)
#gives min number from every column

array([ 7, 18, 35, 48, 18], dtype=int32)

In [53]:
arr1.min(axis=1)
#gives min number from every row

array([33,  7, 18, 62,  8, 26], dtype=int32)

In [55]:
arr1.argmin()
#min or max numbers position/index

np.int64(5)

In [56]:
arr1.argmax()

np.int64(28)

# Operations on array
### Broadcasting - addition of two different dimension array

In [57]:
arr1 = np.array([45,67,12,50])
arr2 = np.array([[10,20,30,40],
                 [50,60,70,80]])
arr3 = arr1 + arr2
arr3

array([[ 55,  87,  42,  90],
       [ 95, 127,  82, 130]])

In [58]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(11,15).reshape(2,2)

In [59]:
arr1

array([[1, 2],
       [3, 4]])

In [60]:
arr2

array([[11, 12],
       [13, 14]])

In [61]:
arr2 - arr1

array([[10, 10],
       [10, 10]])

# Conditional Selection

In [62]:
arr1 = np.random.randint(1,100,15)
arr1

array([46, 11, 48, 47, 38, 68,  7, 23, 49,  8, 80, 90, 72, 70, 37],
      dtype=int32)

In [63]:
arr1 <50

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False, False, False, False,  True])

In [64]:
arr1[arr1 <50]

array([46, 11, 48, 47, 38,  7, 23, 49,  8, 37], dtype=int32)

In [65]:
arr1[arr1 %2 ==0]

array([46, 48, 38, 68,  8, 80, 90, 72, 70], dtype=int32)

In [66]:
arr1[arr1 %3 ==0]

array([48, 90, 72], dtype=int32)

In [67]:
arr1[(arr1 >50) & (arr1 <90)]

array([68, 80, 72, 70], dtype=int32)