In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2],
                 [3,4]])

In [3]:
arr1

array([[1, 2],
       [3, 4]])

In [4]:
arr1[ :,0]

array([1, 3])

In [5]:
arr1[ :,1]

array([2, 4])

In [6]:
arr2 = np.array([arr1[ :,0],
                 arr1[ :,1]])

In [7]:
arr2

array([[1, 3],
       [2, 4]])

In [8]:
arr1.T
#will give you transposed matrix

array([[1, 3],
       [2, 4]])